// Generated by CoffeeScript 1.4.0
var app, port, server;

app = require('./.app');

port = app.port;

server = app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});

// Express 3.0 returns the server after the call to `listen`.
require('./.app/socket-io')(server, app)